import os
os.system("java Reactionsv6 hbr-butene.mol bromo-butane.mol")
os.system("java Reactionsv6 bromo-methyl-cyclopentane.mol methoxy-cyclopentane.mol")
os.system("java Reactionsv6 3-bromo-3-methyl-butene.mol 2-methyl-1,3-butadiene.mol")
os.system("java Reactionsv6 2-benzyl-2-chloro-propane.mol dimethyl-benzyl-methyl-ether.mol")
os.system("java Reactionsv6 aldol\ SM.mol ALDOL\ P.mol")
os.system("java Reactionsv6 reactant_1.mol product_1.mol")
os.system("java Reactionsv6 reactant_2.mol product_2.mol")
os.system("java Reactionsv6 reactant_3.mol product_3.mol")
os.system("java Reactionsv6 reactant_4.mol product_4.mol")
os.system("java Reactionsv6 walker_reactant1.mol walker_product1.mol")
os.system("java Reactionsv6 walker_reactant2.mol walker_product2.mol")
os.system("java Reactionsv6 walker_reactant3.mol walker_product3.mol")
os.system("java Reactionsv6 walker_reactant4.mol walker_product4.mol")
os.system("java Reactionsv6 walker_reactant5.mol walker_product5.mol")
os.system("java Reactionsv6 walker_reactant6.mol walker_product6.mol")
os.system("java Reactionsv6 walker_reactant7.mol walker_product7.mol")
os.system("java Reactionsv6 walker_reactant8.mol walker_product8.mol")

